loop_on_end = true

[defaults]
format = "ğŸ… {name} {state}: {time}\n"
paused_state_text = "paused"
resumed_state_text = "playing"

[[sessions]]
id = "work"
name = "Work"
duration = "30m"
command = "notify-send 'Work Done!'"

[[sessions]]
id = "rest"
name = "Rest"
duration = "5m"
command = "notify-send 'Rest Done!'"

